eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: Film
  datasource:
    url: jdbc:mysql://localhost:3306/hellno?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /Film
  port: 8080
