eureka:
  client:
    register-with-eureka: false
spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: Film
          uri: http://localhost:8080
          predicates:
            - Path=/Film/**
  application:
    name: gateway
server:
  port: 8222
